/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica2;

/**
 *
 * @author aysha
 */
public class Frame extends javax.swing.JFrame {

    public Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jPanel1_projectes.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_projectes = new javax.swing.JPanel();
        jButton1_cavall = new javax.swing.JButton();
        jButton1_reines = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1_projectes.setBackground(new java.awt.Color(204, 204, 255));

        jButton1_cavall.setBackground(new java.awt.Color(204, 255, 255));
        jButton1_cavall.setText("Problema dels cavalls");
        jButton1_cavall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_cavallActionPerformed(evt);
            }
        });

        jButton1_reines.setBackground(new java.awt.Color(204, 255, 255));
        jButton1_reines.setText("Problema de les n reines");
        jButton1_reines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_reinesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_projectesLayout = new javax.swing.GroupLayout(jPanel1_projectes);
        jPanel1_projectes.setLayout(jPanel1_projectesLayout);
        jPanel1_projectesLayout.setHorizontalGroup(
            jPanel1_projectesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_projectesLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel1_projectesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1_reines, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jButton1_cavall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1_projectesLayout.setVerticalGroup(
            jPanel1_projectesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_projectesLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton1_cavall)
                .addGap(45, 45, 45)
                .addComponent(jButton1_reines)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_projectes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_projectes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_cavallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_cavallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_cavallActionPerformed

    private void jButton1_reinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_reinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_reinesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_cavall;
    private javax.swing.JButton jButton1_reines;
    private javax.swing.JPanel jPanel1_projectes;
    // End of variables declaration//GEN-END:variables
}
